version: '3.9'

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      # - DB_HOST=db
      # - DB_NAME=devdb
      # - DB_USER=devuser
      # - DB_PASS=changeme
      - SECRET_KEY=1_dc7z50pjc^@3bngh2v%2^c=e=+o7!b!=f@wau%d+kr$rm)&texi
      - SHOPIFY_BASE_URL=https://antique-tableware.myshopify.com/admin/api/2023-01/
      - ACCESS_TOKEN=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
      - API_KEY=Yoshiyuk-nestshop-PRD-59c70a856-0aa7c56d
      - DEV_ID=ddc975d2-af5c-485a-acbd-07e68fbf8412
      - CERT_ID=PRD-9c70a856ab47-f8d9-41bb-8098-6270
      - RU_NAME=Yoshiyuki_Matsu-Yoshiyuk-nestsh-zvueewlei
      - TOKEN=v^1.1#i^1#f^0#p^3#I^3#r^0#t^H4sIAAAAAAAAAOVZXYwbVxVe7zpLo5AGlfLTUJA7oeJPY98ZezzjydqSd+2sza53Hdv7C2W5M3NnfePxzGTunfUaUWQ2kKggqtKWQlWkpqAitSKg8lAJRWpLK1oRREUqKPCAhAAVhAqh8JAioDDj3XW8S5pk13mwhF+suXP+vu+cc2fOHdAa3vvhk7mTF/cH3jJ4ugVag4EAtw/sHd7zkRuHBg/uGQBdAoHTrfe3gmtDfxwhsG7YcgkR2zIJCq3WDZPI7cUk4zqmbEGCiWzCOiIyVeVyujAp82Eg245FLdUymFA+k2SkWBQkYoiPaVCRQAJ4q+amzYqVZDQe6AonxfW4LmiSqHr3CXFR3iQUmjTJ8ICPsoBjOanC8zKIyzwf5gRpkQnNIodgy/REwoBJtcOV27pOV6xXDhUSghzqGWFS+fSR8nQ6n8lOVUYiXbZSGzyUKaQu2Xo1ZmkoNAsNF13ZDWlLy2VXVREhTCS17mGrUTm9Gcwuwm9THZV0XownND0eFSHihOtC5RHLqUN65Tj8FayxeltURibFtHk1Rj02lGNIpRtXU56JfCbk/x11oYF1jJwkkx1NL8yUsyUmVC4WHWsFa0jzkfIxSRJFnuN5JtW0SNVzS5YS4oabdVsbJG/zM2aZGvYpI6Epi44iL2a0lRlOFrqY8YSmzWknrVM/no5cogJAh0Fu0U/peg5dWjX9rKK6R0OofXl1/jcL4lIJXLeSiCb0mCJJMY8uBcVilykJv9d3XBYpPzPpYjHix4IU2GTr0KkhahtQRazq0evWkYM1OSrovFeXiNXiCZ2NJXSdVQQtznI6QgAhRVET0v9PdVDqYMWlqFMh22+0ISaZsmrZqGgZWG0y20Xa+81GPaySJFOl1JYjkUajEW5Ew5azHOEB4CLzhcmyWkV1yHRk8dWFWdyuDBV5WgTLtGl70ax6hec5N5eZVNTRitChzTIyDG9hs2y3xJbavvomIMcM7DFQ8Vz0F8acRSjSeoJmWMvYLCBatbS+wub3eipbSOcne4LnbTCQ9hWwVFePcrGNHvXeNlggygD0BDZt2/l63aVQMVC+v9KZiomAF6I9wfM3bxlDXaZWDZn9142l7JFStpxbqkxPZKd6QlpCuoNIteLj7LdEpo+mc2nvV8gcm5BGs0IFmStFc7zBG6vpohgBph2vRXLpxXE8Ntds5o5ViwlaLCjaaDwxB6UFi5ApcnyKM8hyMrlBh9/ruyOqjFQH9Vl/F+iCXZPg0fRkftTKcJHmuCIsNKKrVXN2dg7Q2cXxaHGVzCofnZxJ9lQlhWXcZ7XBcwIPuAQvRj21nrBV+rPFnfXGXGrvQEveVU8gs8tuv2VQ4eNaglckThIAVMUoisckTUtwuq5DXVPFnvDaHly/1/sLMqnVjlcJV/depXp++vZZNr3dtoqbbo01EaGkatlssZRhhYQqAigJcRZAKKpCvLc3SOJPAP2F29cnngFo47D/1hBWrXrEgt6I6y8ttSMOXYtQhHjTQ3h9YPQshx0ENcs0mrtR3oEONle8ecNymrtx2FHegQ5UVcs16W7cbaheTsPv9TfR0l1Dx4bhD5a7cdqlvpNQTWg0KVbJrlxi0684sgMVGzbbADVMbL9frknTW6sjR0VhrK0fT+0w2I6+aVGsYxX6hwRh4ipEdbDdPqG5TnY6gfU2oSENO0ilS66D+2sX2dw98VIBUuKy23ZT9lMrLkINA+Ge8Pu09+H8nSqmy+W56VLmGsEF1wZvuDzADFrpt+eipqkJUdB4FuqCysYkAbJQVTRvBEdxSVd0KcbxPSW17w4duLgYA2JCkK75hGHbQtc54P8cAEe2fn9JDbR/3FrgWbAWeGowEAAj4HbuELhteGgmOPTWgwRTb3uDepjgZRNS10HhGmraEDuDbx+4CP7wkPpq7rEv1N5oHH/l8J0D3Z9/Tt8B3t35ALR3iNvX9TUI3Hrpzh7uwLv281HAcRLPgzjPL4JDl+4GuXcGbz72ubto/vy5CxdfePwVtfBcpH5Gy4P9HaFAYM9AcC0w8J4zLeXAg/sO/ei57y19vHHmbS8+9dnVCz8FMz//a2Zi7On7XvrnKfNPuU/j8RuDr52MWb/YNzCaji610G0v3/HdU+975pbHyw/m773AfqI28ewjLah/G8/eWbzhiHR3qfgT7ib3pns+PzKf/9pJ6/yPC49d/Mc3TxRttnHuW8FM6XVnRPvyx+6fz8+v7M2Zjy4yv/zPwNMnaiee+G10beaD1cPDv7uldZjWfv+BuX//4IV/DWtnXz/7q0Bi4pNjLwlR4ez3v14TJWo/Cs4/+esf6l/94ofuu/XFw0/c/fBC/t4HvtRofSP4fONnB37z2gNfOXfw5eefJNm7moG/3P/G8p9PrRx69Z7wO+bf+5kT0t9ufkb6Dv/39Vz+FyjiScaYGwAA

    # depends_on:
    #   - db

  # db:
  #   image: postgres:14-alpine
  #   volumes:
  #     - dev-db-data:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_DB=devdb
  #     - POSTGRES_USER=devuser
  #     - POSTGRES_PASSWORD=changeme
  #     - "TZ=Asia/Tokyo"

volumes:
  dev-db-data: