# Generated by Django 4.0.8 on 2023-01-11 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='product_id',
            new_name='product',
        ),
    ]
